# Numele aplicatiei
spring.application.name=journeysense-backend

# Conectare la Docker PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/journeysensedb
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (creeaza tabelele automat)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.user=admin
spring.flyway.password=password
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://localhost:5432/journeysensedb

logging.level.org.springframework.security=DEBUG