# Numele aplicatiei
spring.application.name=journeysense-backend

# Conectare la Docker PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/journeysensedb
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (creeaza tabelele automat)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect